### ISSUE TITLE
Append to gallery doesn't work

### ISSUE THREAD

**Issue by imaus10** [biometrics/openbr#308]
$ br -algorithm Identity -enroll thing.ut urls.url
    Set algorithm to Identity
    Enrolling thing.ut to urls.url
    100.00%  ELAPSED=00:00:05  REMAINING=00:00:00  COUNT=114038
    $ wc -l urls.url
    114038 urls.url
    $ br -algorithm Identity -enroll thing.ut urls.url[append]
    Set algorithm to Identity
    Enrolling thing.ut to urls.url[append]
    100.00%  ELAPSED=00:00:05  REMAINING=00:00:00  COUNT=114038
    $ wc -l urls.url
    114038 urls.url

Also, this command only saves the contents of the last file:

    $ br -algorithm Identity -enroll thing.ut thing2.ut urls2.url

**Comment by caotto** [comment]
A couple related issues here:
1. -enroll gal1 gal2 target (i.e. mutiple input galleries) is currently broken (this used to be handled in TemplateList::fromGallery, but now we stream the input gallery, so TemplateList::fromGallery isn't called)

2. target[append=true] appears to be broken due to the deferred gallery open changes (i.e. the file being appended to gets opened in 'r', then subsequently we can't write new templates to it)

**Comment by caotto** [comment]
should be addressed by 8db263f  and 50ec841

**Comment by jklontz** [comment]
Thanks @caotto
