### ISSUE TITLE
Errors with LMDB gallery

### ISSUE THREAD

**Issue by bklare** [biometrics/openbr#441]
@caotto FYI - I have experienced a bug with writing out to an LMDB gallery. I am not sure the location of the error at this point, but the issue I experience is as follows: 

When I convert a set of images buffered in a .gal file, with class labels 0 and 1, to an lmdb gallery, the class label is missing for one of these two classes. I am not sure which one b/c it is in the hands of caffe at that point and I have not inspected. However the behavior experienced is summarized in the caffe user group post linked below. 

For now I am sticking to using the `convert_imageset` tool to create LMDB galleries, but I wanted to get this issue noted if others come across the same symptoms. 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/zwSzWucaRkY/bZMIbzT9DQAJ

**Comment by caotto** [comment]
Generally, lmdbGallery maps observed labels to integers (since the "Label"
property can be arbitrary metadata in openbr), and the expected output for
the lmdb table is an integer, so this could go wrong in a few different
ways depending on what exactly you are trying to do.

I promise nothing, but if you can share some metadata you are attempting to
serialize that exhibits this problem I may take a look at it later (or
someone else can, it shouldn't be that hard to figure out).

**Comment by bklare** [comment]
Thanks. I will send you an email with a small gallery file.

**Comment by caotto** [comment]
by the way if we're talking about random bugs with openbr caffe support,
there still needs to be a clone here:

https://github.com/biometrics/openbr/blob/master/openbr/plugins/classification/caffe.cpp#L107

as-is, the constructed cv::Mat aliases the buffer in output, which is bad
(but will only manifest if some specific timing happens)

**Comment by jklontz** [comment]
Fixed in https://github.com/biometrics/openbr/commit/5a05d91cb9e87d81732ab25da6811d053ea90b7c @JordanCheney fyi

**Comment by caotto** [comment]
For me converting the file to lmdb, then back to .flat format, i.e.
br -convert Gallery small.gal small.lmdb
br -convert Gallery small.lmdb small_reg.flat
indicates that the labels are being re-mapped to 1 and 2, instead of 0 and 1.

The exact location the remapping happens is here:
https://github.com/biometrics/openbr/blob/master/openbr/plugins/gallery/lmdb.cpp#L122
you could try changing the value to size() - 1, and see what happens (this should re-map to 0 and 1, not 1 and 2).
Based on the file you gave me, that would reverse the labels in your file (since 1 is observed first), but everything should still work I guess. 

I think really in this case since you are already using integer labels, it would be better to skip re-mapping as either an option of lmdbGallery, or attempt to detect integer labels directly.

**Comment by bklare** [comment]
Interesting. it seems another fix would be for me to zero strings instead
of numbers as class labels.

**Comment by caotto** [comment]
No, that won't really help, per
https://github.com/biometrics/openbr/blob/master/openbr/plugins/gallery/lmdb.cpp#L117
any QVariant convertable to string is remapped (so that includes number and
strings)

The immediate issue is the remap logic is starting from 1 instead of 0
(although there can be other problems, such as inconsistent re-mapping,
based on the order labels are observed in the file, if you care about
consistency across different lmdb files, and aren't just doing training
based on a single lmdb gallery)

**Comment by bklare** [comment]
Is this reason this has not been noticed before is b/c uses have been with
very high class numbers? In other words, a label has been missing from
previous serializations to lmdb but it hasn't been noticed b/c there are so
many other classes.

**Comment by caotto** [comment]
probably. I haven't looked at the impact on the caffe side at all, but if
the starting point is ~10k classes, missing one is not necessarily going to
matter
