### ISSUE TITLE
How to use Clustering algorithms?

### ISSUE THREAD

**Issue by salimafra** [biometrics/openbr#476]
Hi there,

I have feature vectors of images already extracted.
What I would like to do is to use some of your **clustering algorithms** (ex: **OnlineRODTransform**) to see how it will detect cluster of faces.

Is there any documentation on how to use the clustering algorithms given feature vectors?

If you can provide sample code to use or command line instruction that would be really helpful.

Thanks in advance

**Comment by JordanCheney** [comment]
Hello,

OnlineRODTransform expects feature vectors as input and will append cluster
information to a template's metadata. For example, assuming you have stored
your feature vectors in a .gal file already you can run-

br -algorithm "OnlineROD" - enroll feature_vectors.gal clusters.csv

This should return a cluster id and a cluster confidence in the metadata.
The cluster confidence is the Euclidean distance from the sample to the
center of the cluster it was assigned to. Let me know if that doesn't work!

Best,
Jordan

**Comment by salimafra** [comment]
Thanks for the reply!

Can I have the feature vector as a csv file?
Because I'm not sure how to do it in a gal file instead.

**Comment by JordanCheney** [comment]
The csv file is a bit difficult because OpenBR handles csvs in a specific way. I'm assuming when you say a csv you mean something like-

fv1,value,value,value
fv2,value,value,value

OpenBR assumes csvs refer to a list of files on disk with some associated metadata however so that file won't be loaded the way we want. Check out `openbr/plugins/gallery/csv.cpp` for the code on how that works. A .gal file is an OpenBR format that serializes templates to disk. If you enrolled your images using the face recognition algorithm you can enroll directly to a .gal file like this-

`br -algorithm "FaceRecognition" -enroll your_images feature_vectors.gal`

The type of output is always determined by the file extension that you use.

**Comment by salimafra** [comment]
Thanks again.

The problem I have is that I implemented my own feature extraction method and my output is a csv file containing the feature vectors of all images like:

value,value,value,value
value,value,value,value
.....

Is there anyway to create a .gal file given a csv file or from c++ code that extracts features of images one by one?

**Comment by JordanCheney** [comment]
It sounds like you need to create your own gallery. I would start with the
csvGallery is openbr/plugins/gallery/csv.cpp. Your gallery would just read
your csv file and create a template for each line with its matrix data set
to the content of that line.

**Comment by luweishuang** [comment]
can you give some examples to convert csv file to gal file, I tried  "br -convert Gallery ImgFtr.csv ImgFtr.gal" and do "br -algorithm "OnlineROD" - enroll ImgFtr.gal clusters.csv" just got wrong result

**Comment by JordanCheney** [comment]
Hi. It depends on the format of your csv. If your csv is a comma separated
list for scores in your feature vectors (with one vector per row) then
OpenBR doesn't support this currently (because it means you didn't do your
feature vector creation in OpenBR). It is very trivial to write a gallery
for this use case but you would need to do it yourself.

**Comment by luweishuang** [comment]
I have written my own feature to gallery file and tested the algorithm from the terminal as "br -algorithm "OnlineROD" - enroll feature_vectors.gal clusters.csv". Now I want doing it in a cpp file just as app/examples/**.cpp does and counter some errors. could you give some demo codes about  "OnlineROD" algorithm. thanks a lot

**Comment by sklum** [comment]
Apart from what @JordanCheney has already helped with, I'm not sure there's more we can do without more specifics.
