### ISSUE TITLE
AgeEstimation and GenderEstimation help

### ISSUE THREAD

**Issue by lewma** [biometrics/openbr#481]
I built the source fine and it installed fine on my Raspberry Pi 3 running Jessie. I'm now testing the install with a few images.  No matter what image I use, I get a 44yr old Female as the results.  Is the pre-trained models ok ?  Do I have to do any other configuration ?

Running:

br -algorithm AgeEstimation -enroll myfile.jpg out.csv

also

br -algorithm GenderEstimation -enroll myfile.jpg out.csv

any help would be GREATLY appreciated!!
mark

**Comment by lewma** [comment]
As a follow up, do I need to run scripts/downloadDatasets.sh for the models to work ?

**Comment by hhertogh** [comment]
I had the same issue, don't know why it happen, did you find a solution for it?

**Comment by sklum** [comment]
@lewma: You should not need anything from the `downloadDatasets.sh` script for those models to work.  Having said that, I can not replicate your issue with the pretrained models on OSX.  Although I've done some work with OpenBR on RPi, I don't have a machine set up to help debug this.

**Comment by ne0c0de** [comment]
I have the same issue that my openbr is running under Ubuntu 16.04.2 LTS

I installed OpenBR and try to enroll some of my images (for example on this: https://scontent-amt2-1.cdninstagram.com/t51.2885-19/11899492_1651222925128828_902341705_a.jpg) and it recognise me as 45 years old female.

I tried to execute downloadDatasets.sh file and it's failed on some mkdir commands. (The error was it was trying to build a folder that parent folder doesn't exist) even i fixed them and try to run the estimation nothing changed.

Then i tried to execute helloWorld.sh but it's failed on this command and after:

br -algorithm Eigenfaces -path ../data/MEDS/img -compare ../data/MEDS/sigset/MEDS_frontal_target.xml ../data/MEDS/sigset/MEDS_frontal_query.xml scores.mtx

because there's no sigset for MEDS dataset. i don't know how to generate it. I already research google to find it and the only place that i found a related meta data on https://catalog.data.gov/dataset/multiple-encounter-dataset-meds-ii-nist-special-database-32/resource/e7c09c3a-726e-4945-8bfc-8fa196b4166e however there's no sigset for that.

Then i tried to run evalAgeRegression-PCSO.sh however it's failed too because i don't have PCSO database. After my research about it i learnt that it's not a public database that i can retrieve.

So, can you @sklum  please guide us how to train OpenBR especially for age and gender estimation? Also it would be good if there's some explanation in the documentation which is telling about which scripts making of what in the scripts folder.

Thanks
